# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Tech Card
  description: Technology card used for tech stack display
  icon: wysiwyg
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  tech:
    name: ""
    icon: ""
    description: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  tech:
    name: "Python"
    icon: "python.svg"
    description: "Primary backend language for building scalable applications"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
