# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Tech Section
  description: Section displaying developer introduction and tech stack
  icon: wysiwyg
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  description_html: ""
  tech_stack: site.data.tech_stack

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: About Me
  description_html: >-
    <p><strong>Backend developer</strong> with 4 years of experience building
    scalable solutions and automation tools. I specialize in creating efficient
    systems that streamline business processes and enhance productivity.</p>

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
