# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Section
  description: Section displaying information about yourself
  icon: wysiwyg
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  description_html: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: About Me
  description_html: Add your description here

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
