title: Michael Lohier Portfolio
description: >-
  Michael Lohier is a French freelancer specialised in backend development and
  automation.
keywords: portfolio, freelance, development, automation
social_media_share_image: /images/michael_lohier.jpg
disqus-identifier:
google-analytics:
