title: Michael Lohier | Portfolio
description: >
  Michael Lohier is a French freelancer specialised in backend development and
  automation.
social_media_share_image: /images/01.jpg
disqus-identifier:
google-analytics:
