name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
        
    - name: Install Jekyll Dependencies
      run: |
        cd site
        bundle install
    
    - name: Build Bookshop
      run: |
        npm install
        npm run bookshop-hosted
        
    - name: Build Jekyll Site
      run: |
        BUNDLE_GEMFILE=site/Gemfile bundle exec jekyll build --source site
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
      env:
        GIT_TRACE: 1
        GIT_CURL_VERBOSE: 1
